### ISSUE TITLE
Implementar tests

### ISSUE THREAD

**Issue by diegoefe** [codenautas/dir-info#1]
Si getInfo() recibe paths nulos o no son directorios debemos tirar excepciones o devolver el objeto info con, por ejemplo, path:'error' y lo demás 'unknown'?

**Comment by diegoefe** [comment]
Existe un delay siempre al correr los tests por la "before" condition, se nota al ejecutarlo salteando todos

**Comment by emilioplatzer** [comment]
1) excepción, pero no hace falta controlarlo, que dé error naturalmente lo
que tenga que dar error

2) sí, porque cada vez copia la carpeta test/fixtures sobre
test/working-fixtures; no sé si hay una mejor manera. Se me ocurren varias
alternativas pero todas tienen algún issue

**Comment by diegoefe** [comment]
1) ok
2) Era sólo un comentario porque los tests siempre reportan tiempo extra

**Comment by diegoefe** [comment]
El opts.cmd==true sugiere que si vale false no se ejecutan comandos de git pero eso no es así.
Porque sin ejecutarlos no puedo verificar fehacientemente, por ejemplo, que el dir un pull de github.

**Comment by emilioplatzer** [comment]
ok, entonces con cmd==false solo dirá 'git' en vez de 'github' (no sabía
que no se podía solo mirando los archivos).

**Comment by diegoefe** [comment]
No estoy 100% seguro, pero se me ocurrio usar un comando (git config --get remote....) porque si cambia la estructura o las variables del directorio .git, dejaría de funcionar

**Comment by emilioplatzer** [comment]
está bien

2015-05-04 11:27 GMT-03:00 Diego Florio <notifications@github.com>:

**Comment by diegoefe** [comment]
En 'comprehensive incomprehensible tests' hay dos casos que usan:  path:'simple-dir/package.json' que son incompatibles entre sí (además, no debería haber dos), asumo que el correcto es el último.
Faltaría crear uno para server:'ok' pero es difícil porque se romperia con los updates...

**Comment by diegoefe** [comment]
Una posibilidad podría ser correr npm-check-updates -u antes de correr los tests sobre el package.json que debe estar actualizado

**Comment by emilioplatzer** [comment]
De los dos package.json que está en los casos de prueba uno habrá que
actualizarlo a mano manualmente. No te preocupes por eso ahora. Lo hago yo.

Ahí subí un cambio en ese sentido

**Comment by diegoefe** [comment]
Perfecto. Pero me parece mejor automatizarlo porque es desconcertante
correr los tests después de un tiempo (si uno se olvida) y que fallen

2015-05-12 9:40 GMT-03:00 Emilio <notifications@github.com>:

**Comment by emilioplatzer** [comment]
Sí, es mejor. Igual para eso está Travis-CI, para avisar que una prueba deja de pasar. 

Pero hay otras cosas más importantes. No te preocupes, por ahora la actualización la hago a mano.

**Comment by diegoefe** [comment]
oki

2015-05-12 9:52 GMT-03:00 Emilio <notifications@github.com>:

**Comment by emilioplatzer** [comment]
Listo hasta acá, lo nuevo en nuevo issue
