### ISSUE TITLE
Hacer limpieza de extras

### ISSUE THREAD

**Issue by emilioplatzer** [codenautas/dir-info#12]
Para simplificar y viendo la forma en que se usa desde fast-devel-server vamos a simplificar lo que devuelve y vamos a quitar los resúmenes. 

Se van: is, server

**Comment by emilioplatzer** [comment]
Le quité las dos propiedades de prepo al final antes de retornar info. Lo que hay que hacer en realidad es emprolijar todo el código para ya no calcular esas dos propiedades.

**Comment by diegoefe** [comment]
Ok

**Comment by diegoefe** [comment]
Sigo yo?

**Comment by diegoefe** [comment]
Creo que está
