### ISSUE TITLE
Agregar el control de pushPending

### ISSUE THREAD

**Issue by emilioplatzer** [codenautas/dir-info#13]
Agrego un caso de prueba (hay que descomentar la línea marcada después de 
```js
// descomentar para pushPending
```

La carpeta **auto-reference-github-unpushed**  se generó haciendo un pull, luego se borró un archivo (test/test.js), luego se hizo un commit (pero no un push), por lo tanto queda pendiente un push. 

El control syncPush es para esas situaciones (quizás haya que agregar más casos de prueba). O sea después de un pull, modificar, commitear tiene que dar pushPending (que significa se puede hacer un push y el repositorio remoto va a cambiar.

**Comment by emilioplatzer** [comment]
Esto deriva en la siguiente info a recolectar:

  1. **isAhead**, es el caso más común de falta de push
  2. **isDiverged**, es el que se ve en el caso de prueba
  3. **branch**, siempre devuelve el nombre del branch (generalmente es master).

**Comment by diegoefe** [comment]
isAhead debe ser isBehind

**Comment by diegoefe** [comment]
Corrijo: isAhead existe también. Setearé las dos entonces. Difícil hacer un caso de prueba para isAhead

**Comment by diegoefe** [comment]
Implementado con "git log --branches --not --remotes". Cerralo si te parece que alcanza.

**Comment by diegoefe** [comment]
Creo que puede cerrarse.
