### ISSUE TITLE
Arreglar los nombres de archivos en untracked y modifieds

### ISSUE THREAD

**Issue by emilioplatzer** [codenautas/dir-info#14]
Cómo reproducir el error: 
1. clonar fast-devel-server en `c:\hecho\npm\fast-devel-server`
2. agregar hola.txt en fast-devel-server
3. correr `npm start` en fast-devel-server
4. en el navegador poner `localhost:54321/file/fast-devel-server`
5 comprobar acercando el mouse al ícono de modifieds (signo de pregunta en un círculo) que el title dice `untrackeds:el-server/hola.txt` en vez de `untrackes:hola.txt`

Creo que debe haber algo mal en la expresión regular que obtiene el prefijo que hay que quitar al nombre de archivo.

**Comment by emilioplatzer** [comment]
Agregar el caso de prueba.

**Comment by diegoefe** [comment]
Listo. Falta resolver #15 para que no falle si lo corro de un directorio relativo que no contiene un package.json

**Comment by emilioplatzer** [comment]
Volví a hacer los pasos 1 a 5 y sigue andando igual de mal.

**Comment by emilioplatzer** [comment]
Mala mía, faltaba actualizar el package.json
