### ISSUE TITLE
dir-info no soporta nombres de archivo con espacios y caracteres no ASCII7

### ISSUE THREAD

**Issue by emilioplatzer** [codenautas/dir-info#16]
Debe soportarlos. 

Probar con una carpeta que contenga un nombre de archivo con espacio y caracteres no ASCII7

**Comment by emilioplatzer** [comment]
Ojo que lo probé desde fast-devel-server, quizás el problema sea la interacción.

**Comment by emilioplatzer** [comment]
Sí, el log de fast-devel-server dice:
```sh
ERROR [Error: '..\exec-to-html\test\texte%20fran%C3%A7ais.txt' does not exists]
stack Error: '..\exec-to-html\test\texte%20fran%C3%A7ais.txt' does not exists
```
evidentemente alguien no está devolviendo los %xx a su caracter correspondiente.

**Comment by diegoefe** [comment]
El test 'tree-git must recognize git dir' contiene archivos con esas condiciones.
Agregué un pequeño test que acepta un archivo de entrada y parece funcionar (no falla y devuelve lo que corresponde).
Lo que se ve en el comentario anterior parece algo relacionado con urlencoding/decoding (texte%20fran%C3%A7ais.txt) no con ASCII7.
Fijate si podés escribir un test que falle.
