### ISSUE TITLE
error de npm install

### ISSUE THREAD

**Issue by diegoefe** [codenautas/dir-info#18]
Cuando dir-info es utilizado por otro proyecto, npm install falla si git no está en el path

**Comment by emilioplatzer** [comment]
Es correcto. Tiene que fallar de una manera agradable

**Comment by diegoefe** [comment]
El problema es al instalar npm-check-updates (como módulo, para usar el api).
Este módulo usa otro módulo (which) para encontrar git y éste falla.
Lo mismo ocurre al usar dir-info en otro módulo (obviamente)
Es un error de npm, no de dir-info, no creo que podamos capturarlo

**Comment by emilioplatzer** [comment]
Habría que ver si se puede poner una advertencia durante el install. Algo así como un "pre-install": "echo ATENCION git debe estar en el path"

**Comment by diegoefe** [comment]
Ok, me fijo si npm tiene algo
