### ISSUE TITLE
Error aleatorio por saturación en la búsqueda de git

### ISSUE THREAD

**Issue by emilioplatzer** [codenautas/dir-info#20]
Después de días de estar corriendo y usándolo a veces deja de ser funcional y hay que reiniciarlo para poder seguir usándolo. 

El error se pude ver en fast-devel-server y en el log se observa algo como:
```
STACK Error: Command failed: C:\Windows\system32\cmd.exe /s /c "git status -z"
"git" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
 `git status -z` (exited with error code 1)
    at ChildProcess.exithandler (child_process.js:203:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
ERROR { [Error: Command failed: C:\Windows\system32\cmd.exe /s /c "git status -z
```

Revisar que la llamada a git no dependa de establecer variables de ambiente o cosas similares que podrían romperse.

**Comment by diegoefe** [comment]
Siguiendo tu sugerencia revisé y se realizaba un append cada vez que se llamaba a dir-info!
Fijate si querés cerrarlo o si querés esperar un poco para verificarlo

**Comment by emilioplatzer** [comment]
Perfecto. Eso tiene que funcionar. Es muy probable que haya sido eso

**Comment by emilioplatzer** [comment]
Faltaba subir la versión en fast-devel-server para que tome este arreglo. Listo.
