### ISSUE TITLE
No usar el separador de carpetas barra invertida (de windows)

### ISSUE THREAD

**Issue by emilioplatzer** [codenautas/dir-info#3]
Cambiar en el código y en los test `'\\'` por [path.sep](https://nodejs.org/api/path.html#path_path_sep)

Nodejs entiende aún en windows la barra común como separador '/', sin embargo es bueno tener algunos tests que usen el separador del SO. A veces es imprescindible (por ejemplo si se va a a recorrer la variable de ambiente PATH). 

`'\\'` va a hacer que Travis-CI falle

**Comment by diegoefe** [comment]
Entiendo.
En el caso de los tests en los que controlo la entrada y salida (expectCall) no parece grave y permite comprobar que el módulo trabaja con el input exacto, sin modificarlo.
Te parece o aún en ese caso uso path.sep?

**Comment by emilioplatzer** [comment]
Podemos esperar a ver si fallan en Travis-CI

2015-05-11 10:24 GMT-03:00 Diego Florio <notifications@github.com>:

**Comment by diegoefe** [comment]
Ok. Igual a partir de ahora uso siempre path.sep

**Comment by diegoefe** [comment]
En la entrada de los 'comprehensive incomprehensible tests' los paths están todos escritos con el separador de unix, sabemos que funciona porque node los convierte, pero es correcto esto?

**Comment by emilioplatzer** [comment]
Sí. Salvo que uses una función que dependa del SO como la que normaliza el
path
