### ISSUE TITLE
Timeout excesivo

### ISSUE THREAD

**Issue by diegoefe** [codenautas/dir-info#7]
Para el test 'comprehensive incomprehensible tests' tuve que agrandar el timeout.
Alguna sugerencia para resolver esto?

**Comment by emilioplatzer** [comment]
Por ahora no. Está bien cambiar el timeout para las pruebas que lo
necesiten.

**Comment by diegoefe** [comment]
Con este commit e3820107c5a5e3378b6753e32564a9f2c17e89e2 se redujo unos segundos el tiempo de tests
